# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-03 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datahora',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='Id', primary_key=True, serialize=False)),
                ('dia', models.IntegerField(blank=True, db_column='Dia', null=True)),
                ('mes', models.IntegerField(blank=True, db_column='Mes', null=True)),
                ('ano', models.IntegerField(blank=True, db_column='Ano', null=True)),
                ('hora', models.IntegerField(blank=True, db_column='Hora', null=True)),
                ('minutos', models.IntegerField(blank=True, db_column='Minutos', null=True)),
                ('segundos', models.IntegerField(blank=True, db_column='Segundos', null=True)),
                ('milissegundos', models.IntegerField(blank=True, db_column='Milissegundos', null=True)),
            ],
            options={
                'db_table': 'DataHora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='Id', primary_key=True, serialize=False)),
                ('nome', models.IntegerField(blank=True, db_column='Nome', null=True)),
                ('tipo', models.TextField(blank=True, db_column='Tipo', null=True)),
                ('x', models.IntegerField(blank=True, db_column='X', null=True)),
                ('y', models.IntegerField(blank=True, db_column='Y', null=True)),
                ('width', models.IntegerField(blank=True, db_column='Width', null=True)),
                ('height', models.IntegerField(blank=True, db_column='Height', null=True)),
            ],
            options={
                'db_table': 'Local',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medidafinal',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='Id', primary_key=True, serialize=False)),
                ('width', models.IntegerField(blank=True, db_column='Width', null=True)),
                ('height', models.IntegerField(blank=True, db_column='Height', null=True)),
            ],
            options={
                'db_table': 'MedidaFinal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Numeropessoasquadrante',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='Id', primary_key=True, serialize=False)),
                ('num_de_pessoas', models.IntegerField(blank=True, db_column='Num_de_Pessoas', null=True)),
            ],
            options={
                'db_table': 'NumeroPessoasQuadrante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Numeropessoastotal',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='Id', primary_key=True, serialize=False)),
                ('num_de_pessoas', models.IntegerField(blank=True, db_column='Num_de_Pessoas', null=True)),
            ],
            options={
                'db_table': 'NumeroPessoasTotal',
                'managed': False,
            },
        ),
    ]
