# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-08 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posicao',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='Id', primary_key=True, serialize=False)),
                ('x', models.IntegerField(blank=True, db_column='X', null=True)),
                ('y', models.IntegerField(blank=True, db_column='Y', null=True)),
                ('instante_inicial', models.IntegerField(blank=True, db_column='Instante_Inicial', null=True)),
                ('instante_final', models.IntegerField(blank=True, db_column='Instante_Final', null=True)),
                ('atual', models.IntegerField(blank=True, db_column='Atual', null=True)),
                ('pessoa_id', models.IntegerField(blank=True, db_column='Pessoa_id', null=True)),
            ],
            options={
                'db_table': 'Posicao',
                'managed': False,
            },
        ),
    ]
